# AdWords Keyword Generator

This notebook will show how to train algorithms capable to create keywords for DataCamp marketing campaigns. This is based on a DataCamp tutorial: https://www.datacamp.com/community/tutorials/sem-data-science

## Imports

In [10]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

## Data preparation

In [2]:
instructors_page = 'https://www.datacamp.com/instructors?all=true';
instructor_link_selector = '.instructor-block__description .instructor-block__link'; # Link class BEM styled (block, element (-), modifier (__))
instructor_name_selector = '.mb-sm'; # Instructor name class

In [3]:
# Get information on the instructors page at DataCamp
instructor_resp = requests.get(instructors_page)

In [8]:
# Generate a beautiful soup object
soup = BeautifulSoup(instructor_resp.text, 'html5lib')

In [9]:
# Extract the information that will be used to generate Dataframes that will be used to create ads
instructor_urls = [url['href'] for url in soup.select(instructor_link_selector)]
instructor_names = [name.text.strip() for name in soup.select(instructor_name_selector)]
instructor_urls = ['https://www.datacamp.com' + url for url in instructor_urls]

In [12]:
# Build the Dataframe
instructor_df = pd.DataFrame({
    'name': instructor_names,
    'url': instructor_urls
})

In [13]:
# Print the shape of the Dataframe
print(instructor_df.shape)

(74, 2)

In [14]:
# Show the first registers in the Dataframe
instructor_df.head()

                   name                                                url
0    Filip Schouwenaars      https://www.datacamp.com/instructors/filipsch
1  Jonathan Cornelissen  https://www.datacamp.com/instructors/jonathana...
2   Hugo Bowne-Anderson     https://www.datacamp.com/instructors/hugobowne
3         Nick Carchedi        https://www.datacamp.com/instructors/nickyc
4       Dhavide Aruliah     https://www.datacamp.com/instructors/continuum

In [16]:
# Generate keywords for courses and instructors
col_names = ['Campaign', 'Ad Group', 'Keyword', 'Criterion Type'] # Headers to be uploaded on Google AdWords
words = ['course', 'courses', 'learn', 'data science', 'data camp', 'datacamp'] # Words to be combined with instructors to generate keywords
match_types = ['Exact', 'Phrase', 'Broad'] # Keyword match type in Google AdWords

In [17]:
# Create a campaign with ad groups and keywords
instructor_keywords = []
for instructor in instructor_df['name']:
    for word in words:
        for match in match_types:
            if match == 'Broad':
                keyword = '+' + ' +'.join([word, instructor.replace(' ', ' +').lower()])
            else:
                keyword = instructor.lower() + ' ' + word
                
            row = ['SEM_Instructors', instructor, keyword, match]
            instructor_keywords.append(row)

In [18]:
# Generate a Dataframe from the array of instructors and keywords
instructors_keywords_df = pd.DataFrame.from_records(instructor_keywords, columns=col_names)

In [19]:
# Print the total number of generated keywords
print('Total keywords: ', instructors_keywords_df.shape[0])

Total keywords:  1332

In [20]:
# Inspect the first five rows of the Dataframe
instructors_keywords_df.head()

,Campaign,Ad Group,Keyword,Criterion Type
0,SEM_Instructors,Filip Schouwenaars,filip schouwenaars course,Exact
1,SEM_Instructors,Filip Schouwenaars,filip schouwenaars course,Phrase
2,SEM_Instructors,Filip Schouwenaars,+course +filip +schouwenaars,Broad
3,SEM_Instructors,Filip Schouwenaars,filip schouwenaars courses,Exact
4,SEM_Instructors,Filip Schouwenaars,filip schouwenaars courses,Phrase

In [32]:
# Refactor the above code to be inside a function so it can be reused
def generate_keywords(topics, keywords, match_types=['Exact', 'Phrase', 'Broad'], campaign='SEM_Campaign'):
    col_names = ['Campaign', 'Ad Group', 'Keyword', 'Criterion Type']
    campaign_keywords = []
    
    for topic in topics:
        for word in keywords:
            for match in match_types:
                if match == 'Broad':
                    keyword = '+' + ' +'.join([topic.lower().replace(' ', ' +'), word.replace(' ', ' +')])
                else:
                    keyword = topic.lower() + ' ' + word
                    
                row = [campaign, topic, keyword, match]
                campaign_keywords.append(row)
                
    for topic in topics:
        for word in keywords:
            for match in match_types:
                if match == 'Broad':
                    keyword = '+' + ' +'.join([word.replace(' ', ' +'), topic.lower().replace(' ', ' +')])
                else:
                    keyword = word + ' ' + topic.lower()
            
                row = [campaign, topic, keyword, match]
                campaign_keywords.append(row)
            
    return pd.DataFrame.from_records(campaign_keywords, columns=col_names)

In [33]:
# Generate keywords for Data Science and Machine Learning topics
topics = ['Data Science', 'Machine Learning']
keywords = ['course', 'tutorial']
generate_keywords(topics, keywords)

,Campaign,Ad Group,Keyword,Criterion Type
0,SEM_Campaign,Data Science,data science course,Exact
1,SEM_Campaign,Data Science,data science course,Phrase
2,SEM_Campaign,Data Science,+data +science +course,Broad
3,SEM_Campaign,Data Science,data science tutorial,Exact
4,SEM_Campaign,Data Science,data science tutorial,Phrase
5,SEM_Campaign,Data Science,+data +science +tutorial,Broad
6,SEM_Campaign,Machine Learning,machine learning course,Exact
7,SEM_Campaign,Machine Learning,machine learning course,Phrase
8,SEM_Campaign,Machine Learning,+machine +learning +course,Broad
9,SEM_Campaign,Machine Learning,machine learning tutorial,Exact
10,SEM_Campaign,Machine Learning,machine learning tutorial,Phrase
11,SEM_Campaign,Machine Learning,+machine +learning +tutorial,Broad
12,SEM_Campaign,Data Science,course data science,Exact
13,SEM_Campaign,Data Science,course data science,Phrase
14,SEM_Campaign,Data Science,+course +data +science,Broad
15,SEM_Campaign,Data Science,tutorial data science,Exact
16,SEM_Campaign,Data Science,tutorial data science,Phrase
17,SEM_Campaign,Data Science,+tutorial +data +science,Broad
18,SEM_Campaign,Machine Learning,course machine learning,Exact
19,SEM_Campaign,Machine Learning,course machine learning,Phrase
20,SEM_Campaign,Machine Learning,+course +machine +learning,Broad
21,SEM_Campaign,Machine Learning,tutorial machine learning,Exact
22,SEM_Campaign,Machine Learning,tutorial machine learning,Phrase
23,SEM_Campaign,Machine Learning,+tutorial +machine +learning,Broad